RandomForestClassifier:
  class: sklearn.ensemble.RandomForestClassifier
  params:
    n_estimators: [10, 20, 40, 80, 160, 320, 640]
    min_samples_leaf: [1, 3, 5, 7, 13]
    max_features: ["log2"]
    criterion: ["gini", "entropy"]
